import http from 'k6/http';
import { check } from 'k6';
import { Counter, Trend } from 'k6/metrics';
import { SharedArray } from 'k6/data';

export const entrySuccess = new Counter('entry_success');
export const entryDuplicate = new Counter('entry_duplicate');
export const entryError = new Counter('entry_error');
export const entryDuration = new Trend('entry_duration');

// Payloads loaded from JSON file generated by seed_matrix.go
const payloads = new SharedArray('entry_payloads', function () {
  const configName = __ENV.CONFIG_NAME || 'unified_guestlinked_presnt';
  return JSON.parse(open(`../payloads_${configName}.json`));
});

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';

export const options = {
  scenarios: {
    entry_load: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '10s', target: 1000 },
        { duration: '10s', target: 5000 },
        { duration: '10s', target: 10000 },
        { duration: '30s', target: 10000 },
        { duration: '10s', target: 0 },
      ],
    },
  },
  thresholds: {
    http_req_failed: ['rate==0'],
    http_req_duration: ['p(95)<200'],
    entry_error: ['count==0'],
  },
};

export default function () {
  const idx = __VU - 1;
  const payload = payloads[idx % payloads.length];
  const entryKey = __ENV.ENTRY_KEY || 'entry_payload';

  const res = http.post(
    `${BASE_URL}/api/v1/scan/entry`,
    JSON.stringify({
      qr_payload: payload[entryKey] || payload.unified_payload || payload.qr_payload,
      stall_id: payload.entry_stall_id || 'stall_entry_01',
      device_id: `device_k6_entry_${__VU}`,
    }),
    {
      headers: { 'Content-Type': 'application/json' },
      timeout: '5s',
    },
  );

  entryDuration.add(res.timings.duration);

  check(res, {
    'entry status is 200 or 409': (r) => r.status === 200 || r.status === 409,
    'entry response has status': (r) => {
      try {
        const body = JSON.parse(r.body);
        return body.status === 'valid' || body.status === 'duplicate';
      } catch (e) {
        return false;
      }
    },
  });

  if (res.status === 200) entrySuccess.add(1);
  else if (res.status === 409) entryDuplicate.add(1);
  else entryError.add(1);
}
