/* eslint-disable */
/**
 * Generated by convex dev. Will be overwritten by `npx convex dev`.
 * This is a stub file for development until a Convex deployment is connected.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

// Stub types that will be replaced by real generated types
declare const fullApi: any;
declare const internal: any;
declare const components: any;

export { fullApi as api, internal, components };
