/* eslint-disable */
/**
 * Generated by convex dev. Will be overwritten by `npx convex dev`.
 * This is a stub file for development until a Convex deployment is connected.
 */

// Stub API module - will be replaced when `npx convex dev` runs
export const api = new Proxy(
  {},
  {
    get: (_target, prop) =>
      new Proxy(
        {},
        {
          get: (_t, method) => `${String(prop)}.${String(method)}`,
        },
      ),
  },
);

export const internal = new Proxy(
  {},
  {
    get: (_target, prop) =>
      new Proxy(
        {},
        {
          get: (_t, method) => `${String(prop)}.${String(method)}`,
        },
      ),
  },
);

export const components = new Proxy(
  {},
  {
    get: (_target, prop) => new Proxy({}, { get: (_t, method) => `${String(prop)}.${String(method)}` }),
  },
);
