/* eslint-disable */
/**
 * Generated by convex dev. Will be overwritten by `npx convex dev`.
 * This is a stub file for development until a Convex deployment is connected.
 */

import type { GenericDataModel, GenericId } from "convex/server";

// Stub DataModel - will be replaced by real generated types
export type DataModel = GenericDataModel;
export type Id<TableName extends string> = GenericId<TableName>;
