/* eslint-disable */
/**
 * Generated by convex dev. Will be overwritten by `npx convex dev`.
 * This is a stub file for development until a Convex deployment is connected.
 */

export {
  query,
  mutation,
  action,
  internalQuery,
  internalMutation,
  internalAction,
  httpAction,
} from "convex/server";

export type {
  QueryCtx,
  MutationCtx,
  ActionCtx,
} from "convex/server";
