/* eslint-disable */
/**
 * Generated by convex dev. Will be overwritten by `npx convex dev`.
 * This is a stub file for development until a Convex deployment is connected.
 */

// Re-export from convex/server for stub compatibility
export {
  query,
  mutation,
  action,
  internalQuery,
  internalMutation,
  internalAction,
  httpAction,
} from "convex/server";
