/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SizingGuideRouteImport } from './routes/sizing-guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScannerIndexRouteImport } from './routes/scanner/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as EventsEventIdCardsRouteImport } from './routes/events/$eventId/cards'
import { Route as EventsEventIdGuestsIndexRouteImport } from './routes/events/$eventId/guests/index'
import { Route as EventsEventIdGuestsImportRouteImport } from './routes/events/$eventId/guests/import'

const SizingGuideRoute = SizingGuideRouteImport.update({
  id: '/sizing-guide',
  path: '/sizing-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerIndexRoute = ScannerIndexRouteImport.update({
  id: '/scanner/',
  path: '/scanner/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdCardsRoute = EventsEventIdCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdGuestsIndexRoute =
  EventsEventIdGuestsIndexRouteImport.update({
    id: '/guests/',
    path: '/guests/',
    getParentRoute: () => EventsEventIdRoute,
  } as any)
const EventsEventIdGuestsImportRoute =
  EventsEventIdGuestsImportRouteImport.update({
    id: '/guests/import',
    path: '/guests/import',
    getParentRoute: () => EventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sizing-guide': typeof SizingGuideRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/': typeof EventsIndexRoute
  '/scanner/': typeof ScannerIndexRoute
  '/events/$eventId/cards': typeof EventsEventIdCardsRoute
  '/events/$eventId/guests/import': typeof EventsEventIdGuestsImportRoute
  '/events/$eventId/guests/': typeof EventsEventIdGuestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sizing-guide': typeof SizingGuideRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events': typeof EventsIndexRoute
  '/scanner': typeof ScannerIndexRoute
  '/events/$eventId/cards': typeof EventsEventIdCardsRoute
  '/events/$eventId/guests/import': typeof EventsEventIdGuestsImportRoute
  '/events/$eventId/guests': typeof EventsEventIdGuestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sizing-guide': typeof SizingGuideRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/': typeof EventsIndexRoute
  '/scanner/': typeof ScannerIndexRoute
  '/events/$eventId/cards': typeof EventsEventIdCardsRoute
  '/events/$eventId/guests/import': typeof EventsEventIdGuestsImportRoute
  '/events/$eventId/guests/': typeof EventsEventIdGuestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sizing-guide'
    | '/events/$eventId'
    | '/events/'
    | '/scanner/'
    | '/events/$eventId/cards'
    | '/events/$eventId/guests/import'
    | '/events/$eventId/guests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sizing-guide'
    | '/events/$eventId'
    | '/events'
    | '/scanner'
    | '/events/$eventId/cards'
    | '/events/$eventId/guests/import'
    | '/events/$eventId/guests'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/sizing-guide'
    | '/events/$eventId'
    | '/events/'
    | '/scanner/'
    | '/events/$eventId/cards'
    | '/events/$eventId/guests/import'
    | '/events/$eventId/guests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SizingGuideRoute: typeof SizingGuideRoute
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
  EventsIndexRoute: typeof EventsIndexRoute
  ScannerIndexRoute: typeof ScannerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sizing-guide': {
      id: '/sizing-guide'
      path: '/sizing-guide'
      fullPath: '/sizing-guide'
      preLoaderRoute: typeof SizingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/': {
      id: '/scanner/'
      path: '/scanner'
      fullPath: '/scanner/'
      preLoaderRoute: typeof ScannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/cards': {
      id: '/events/$eventId/cards'
      path: '/cards'
      fullPath: '/events/$eventId/cards'
      preLoaderRoute: typeof EventsEventIdCardsRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/guests/': {
      id: '/events/$eventId/guests/'
      path: '/guests'
      fullPath: '/events/$eventId/guests/'
      preLoaderRoute: typeof EventsEventIdGuestsIndexRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/guests/import': {
      id: '/events/$eventId/guests/import'
      path: '/guests/import'
      fullPath: '/events/$eventId/guests/import'
      preLoaderRoute: typeof EventsEventIdGuestsImportRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
  }
}

interface EventsEventIdRouteChildren {
  EventsEventIdCardsRoute: typeof EventsEventIdCardsRoute
  EventsEventIdGuestsImportRoute: typeof EventsEventIdGuestsImportRoute
  EventsEventIdGuestsIndexRoute: typeof EventsEventIdGuestsIndexRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdCardsRoute: EventsEventIdCardsRoute,
  EventsEventIdGuestsImportRoute: EventsEventIdGuestsImportRoute,
  EventsEventIdGuestsIndexRoute: EventsEventIdGuestsIndexRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SizingGuideRoute: SizingGuideRoute,
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
  EventsIndexRoute: EventsIndexRoute,
  ScannerIndexRoute: ScannerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
