// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: food_scans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFoodConsumptionCounts = `-- name: GetFoodConsumptionCounts :many
SELECT food_category_id, COUNT(*)::integer as count
FROM food_scans
WHERE event_id = $1
  AND guest_id = $2
  AND status = 'valid'
GROUP BY food_category_id
`

type GetFoodConsumptionCountsParams struct {
	EventID string `json:"event_id"`
	GuestID string `json:"guest_id"`
}

type GetFoodConsumptionCountsRow struct {
	FoodCategoryID string `json:"food_category_id"`
	Count          int32  `json:"count"`
}

func (q *Queries) GetFoodConsumptionCounts(ctx context.Context, arg GetFoodConsumptionCountsParams) ([]GetFoodConsumptionCountsRow, error) {
	rows, err := q.db.Query(ctx, getFoodConsumptionCounts, arg.EventID, arg.GuestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFoodConsumptionCountsRow
	for rows.Next() {
		var i GetFoodConsumptionCountsRow
		if err := rows.Scan(&i.FoodCategoryID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodConsumptionHistory = `-- name: GetFoodConsumptionHistory :many
SELECT food_category_id, stall_id, scanned_at
FROM food_scans
WHERE event_id = $1
  AND guest_id = $2
  AND food_category_id = $3
  AND status = 'valid'
ORDER BY scanned_at DESC
LIMIT 10
`

type GetFoodConsumptionHistoryParams struct {
	EventID        string `json:"event_id"`
	GuestID        string `json:"guest_id"`
	FoodCategoryID string `json:"food_category_id"`
}

type GetFoodConsumptionHistoryRow struct {
	FoodCategoryID string             `json:"food_category_id"`
	StallID        string             `json:"stall_id"`
	ScannedAt      pgtype.Timestamptz `json:"scanned_at"`
}

func (q *Queries) GetFoodConsumptionHistory(ctx context.Context, arg GetFoodConsumptionHistoryParams) ([]GetFoodConsumptionHistoryRow, error) {
	rows, err := q.db.Query(ctx, getFoodConsumptionHistory, arg.EventID, arg.GuestID, arg.FoodCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFoodConsumptionHistoryRow
	for rows.Next() {
		var i GetFoodConsumptionHistoryRow
		if err := rows.Scan(&i.FoodCategoryID, &i.StallID, &i.ScannedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodConsumptionPerGuest = `-- name: GetFoodConsumptionPerGuest :many
SELECT guest_id, food_category_id, COUNT(*)::integer as consumed
FROM food_scans
WHERE event_id = $1
  AND status = 'valid'
GROUP BY guest_id, food_category_id
`

type GetFoodConsumptionPerGuestRow struct {
	GuestID        string `json:"guest_id"`
	FoodCategoryID string `json:"food_category_id"`
	Consumed       int32  `json:"consumed"`
}

func (q *Queries) GetFoodConsumptionPerGuest(ctx context.Context, eventID string) ([]GetFoodConsumptionPerGuestRow, error) {
	rows, err := q.db.Query(ctx, getFoodConsumptionPerGuest, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFoodConsumptionPerGuestRow
	for rows.Next() {
		var i GetFoodConsumptionPerGuestRow
		if err := rows.Scan(&i.GuestID, &i.FoodCategoryID, &i.Consumed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodCountersByCategory = `-- name: GetFoodCountersByCategory :many
SELECT food_category_id, COUNT(*)::integer as total_served
FROM food_scans
WHERE event_id = $1
  AND status = 'valid'
GROUP BY food_category_id
`

type GetFoodCountersByCategoryRow struct {
	FoodCategoryID string `json:"food_category_id"`
	TotalServed    int32  `json:"total_served"`
}

func (q *Queries) GetFoodCountersByCategory(ctx context.Context, eventID string) ([]GetFoodCountersByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getFoodCountersByCategory, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFoodCountersByCategoryRow
	for rows.Next() {
		var i GetFoodCountersByCategoryRow
		if err := rows.Scan(&i.FoodCategoryID, &i.TotalServed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodCountersByStall = `-- name: GetFoodCountersByStall :many
SELECT stall_id, COUNT(*)::integer as total_served
FROM food_scans
WHERE event_id = $1
  AND status = 'valid'
GROUP BY stall_id
`

type GetFoodCountersByStallRow struct {
	StallID     string `json:"stall_id"`
	TotalServed int32  `json:"total_served"`
}

func (q *Queries) GetFoodCountersByStall(ctx context.Context, eventID string) ([]GetFoodCountersByStallRow, error) {
	rows, err := q.db.Query(ctx, getFoodCountersByStall, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFoodCountersByStallRow
	for rows.Next() {
		var i GetFoodCountersByStallRow
		if err := rows.Scan(&i.StallID, &i.TotalServed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFoodScan = `-- name: InsertFoodScan :one
INSERT INTO food_scans (
    idempotency_key, event_id, guest_id, food_category_id,
    stall_id, scanned_at, device_id, guest_category,
    is_anonymous, consumption_count, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, idempotency_key, event_id, guest_id, food_category_id, stall_id, scanned_at, synced_at, device_id, guest_category, is_anonymous, consumption_count, status
`

type InsertFoodScanParams struct {
	IdempotencyKey   string             `json:"idempotency_key"`
	EventID          string             `json:"event_id"`
	GuestID          string             `json:"guest_id"`
	FoodCategoryID   string             `json:"food_category_id"`
	StallID          string             `json:"stall_id"`
	ScannedAt        pgtype.Timestamptz `json:"scanned_at"`
	DeviceID         string             `json:"device_id"`
	GuestCategory    string             `json:"guest_category"`
	IsAnonymous      bool               `json:"is_anonymous"`
	ConsumptionCount int32              `json:"consumption_count"`
	Status           string             `json:"status"`
}

func (q *Queries) InsertFoodScan(ctx context.Context, arg InsertFoodScanParams) (FoodScan, error) {
	row := q.db.QueryRow(ctx, insertFoodScan,
		arg.IdempotencyKey,
		arg.EventID,
		arg.GuestID,
		arg.FoodCategoryID,
		arg.StallID,
		arg.ScannedAt,
		arg.DeviceID,
		arg.GuestCategory,
		arg.IsAnonymous,
		arg.ConsumptionCount,
		arg.Status,
	)
	var i FoodScan
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.EventID,
		&i.GuestID,
		&i.FoodCategoryID,
		&i.StallID,
		&i.ScannedAt,
		&i.SyncedAt,
		&i.DeviceID,
		&i.GuestCategory,
		&i.IsAnonymous,
		&i.ConsumptionCount,
		&i.Status,
	)
	return i, err
}
