// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EntryScan struct {
	ID             pgtype.UUID        `json:"id"`
	IdempotencyKey string             `json:"idempotency_key"`
	EventID        string             `json:"event_id"`
	GuestID        string             `json:"guest_id"`
	StallID        string             `json:"stall_id"`
	ScannedAt      pgtype.Timestamptz `json:"scanned_at"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
	DeviceID       string             `json:"device_id"`
	Status         string             `json:"status"`
	GuestCategory  string             `json:"guest_category"`
}

type EventCounter struct {
	EventID    string             `json:"event_id"`
	CounterKey string             `json:"counter_key"`
	Value      int64              `json:"value"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
