// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountEntryScansByCategory(ctx context.Context, eventID string) ([]CountEntryScansByCategoryRow, error)
	CountEntryScansByEvent(ctx context.Context, eventID string) (int64, error)
	GetCheckedInGuestIDs(ctx context.Context, eventID string) ([]string, error)
	GetEntryScanByGuest(ctx context.Context, arg GetEntryScanByGuestParams) (EntryScan, error)
	GetFoodConsumptionCounts(ctx context.Context, arg GetFoodConsumptionCountsParams) ([]GetFoodConsumptionCountsRow, error)
	GetFoodConsumptionHistory(ctx context.Context, arg GetFoodConsumptionHistoryParams) ([]GetFoodConsumptionHistoryRow, error)
	GetFoodConsumptionPerGuest(ctx context.Context, eventID string) ([]GetFoodConsumptionPerGuestRow, error)
	GetFoodCountersByCategory(ctx context.Context, eventID string) ([]GetFoodCountersByCategoryRow, error)
	GetFoodCountersByStall(ctx context.Context, eventID string) ([]GetFoodCountersByStallRow, error)
	InsertEntryScan(ctx context.Context, arg InsertEntryScanParams) (EntryScan, error)
	InsertFoodScan(ctx context.Context, arg InsertFoodScanParams) (FoodScan, error)
	UpsertEventCounter(ctx context.Context, arg UpsertEventCounterParams) error
}

var _ Querier = (*Queries)(nil)
