// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountEntryScansByCategory(ctx context.Context, eventID string) ([]CountEntryScansByCategoryRow, error)
	CountEntryScansByEvent(ctx context.Context, eventID string) (int64, error)
	GetCheckedInGuestIDs(ctx context.Context, eventID string) ([]string, error)
	GetEntryScanByGuest(ctx context.Context, arg GetEntryScanByGuestParams) (EntryScan, error)
	InsertEntryScan(ctx context.Context, arg InsertEntryScanParams) (EntryScan, error)
	UpsertEventCounter(ctx context.Context, arg UpsertEventCounterParams) error
}

var _ Querier = (*Queries)(nil)
