// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEntryScansByCategory = `-- name: CountEntryScansByCategory :many
SELECT guest_category, COUNT(*) as total
FROM entry_scans
WHERE event_id = $1 AND status = 'valid'
GROUP BY guest_category
`

type CountEntryScansByCategoryRow struct {
	GuestCategory string `json:"guest_category"`
	Total         int64  `json:"total"`
}

func (q *Queries) CountEntryScansByCategory(ctx context.Context, eventID string) ([]CountEntryScansByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countEntryScansByCategory, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountEntryScansByCategoryRow
	for rows.Next() {
		var i CountEntryScansByCategoryRow
		if err := rows.Scan(&i.GuestCategory, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEntryScansByEvent = `-- name: CountEntryScansByEvent :one
SELECT COUNT(*) as total FROM entry_scans
WHERE event_id = $1 AND status = 'valid'
`

func (q *Queries) CountEntryScansByEvent(ctx context.Context, eventID string) (int64, error) {
	row := q.db.QueryRow(ctx, countEntryScansByEvent, eventID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getCheckedInGuestIDs = `-- name: GetCheckedInGuestIDs :many
SELECT guest_id FROM entry_scans
WHERE event_id = $1 AND status = 'valid'
`

func (q *Queries) GetCheckedInGuestIDs(ctx context.Context, eventID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getCheckedInGuestIDs, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var guest_id string
		if err := rows.Scan(&guest_id); err != nil {
			return nil, err
		}
		items = append(items, guest_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryScanByGuest = `-- name: GetEntryScanByGuest :one
SELECT id, idempotency_key, event_id, guest_id, stall_id, scanned_at, synced_at, device_id, status, guest_category, additional_guests FROM entry_scans
WHERE event_id = $1 AND guest_id = $2
ORDER BY scanned_at DESC
LIMIT 1
`

type GetEntryScanByGuestParams struct {
	EventID string `json:"event_id"`
	GuestID string `json:"guest_id"`
}

func (q *Queries) GetEntryScanByGuest(ctx context.Context, arg GetEntryScanByGuestParams) (EntryScan, error) {
	row := q.db.QueryRow(ctx, getEntryScanByGuest, arg.EventID, arg.GuestID)
	var i EntryScan
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.EventID,
		&i.GuestID,
		&i.StallID,
		&i.ScannedAt,
		&i.SyncedAt,
		&i.DeviceID,
		&i.Status,
		&i.GuestCategory,
		&i.AdditionalGuests,
	)
	return i, err
}

const insertEntryScan = `-- name: InsertEntryScan :one
INSERT INTO entry_scans (idempotency_key, event_id, guest_id, stall_id, scanned_at, device_id, status, guest_category, additional_guests)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, idempotency_key, event_id, guest_id, stall_id, scanned_at, synced_at, device_id, status, guest_category, additional_guests
`

type InsertEntryScanParams struct {
	IdempotencyKey   string             `json:"idempotency_key"`
	EventID          string             `json:"event_id"`
	GuestID          string             `json:"guest_id"`
	StallID          string             `json:"stall_id"`
	ScannedAt        pgtype.Timestamptz `json:"scanned_at"`
	DeviceID         string             `json:"device_id"`
	Status           string             `json:"status"`
	GuestCategory    string             `json:"guest_category"`
	AdditionalGuests int32              `json:"additional_guests"`
}

func (q *Queries) InsertEntryScan(ctx context.Context, arg InsertEntryScanParams) (EntryScan, error) {
	row := q.db.QueryRow(ctx, insertEntryScan,
		arg.IdempotencyKey,
		arg.EventID,
		arg.GuestID,
		arg.StallID,
		arg.ScannedAt,
		arg.DeviceID,
		arg.Status,
		arg.GuestCategory,
		arg.AdditionalGuests,
	)
	var i EntryScan
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.EventID,
		&i.GuestID,
		&i.StallID,
		&i.ScannedAt,
		&i.SyncedAt,
		&i.DeviceID,
		&i.Status,
		&i.GuestCategory,
		&i.AdditionalGuests,
	)
	return i, err
}

const upsertEventCounter = `-- name: UpsertEventCounter :exec
INSERT INTO event_counters (event_id, counter_key, value, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (event_id, counter_key) DO UPDATE
SET value = $3, updated_at = NOW()
`

type UpsertEventCounterParams struct {
	EventID    string `json:"event_id"`
	CounterKey string `json:"counter_key"`
	Value      int64  `json:"value"`
}

func (q *Queries) UpsertEventCounter(ctx context.Context, arg UpsertEventCounterParams) error {
	_, err := q.db.Exec(ctx, upsertEventCounter, arg.EventID, arg.CounterKey, arg.Value)
	return err
}
